#!/usr/bin/env bash
# why you no love me

trap "echo I hate the kill command & rm /var/run/holbertonscript.pid & exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm /var/run/holbertonscript.pid & exit' SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while true; do
    echo To infinity and beyond
    sleep 2
done