#!/usr/bin/env bash
# Uses while loop to print Holberton school 10 times
# and has if/elif/else statement
x=1
while [ $x -le 10 ]
do
    if [[ $x -eq 4 ]]; then
        echo "bad luck"
    elif [[ $x -eq 8 ]]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    x=$(( x + 1 ))
done